# Numpy Basics


In [1]:
import numpy as np
import time as t
arr = np.array([1, 2, 3, 4, 5])

print(f"Numpy array (arr): {arr}")

Numpy array (arr): [1 2 3 4 5]


## Checking Numpy Version


In [2]:
print(f"Numpy version: {np.__version__}")

Numpy version: 2.4.4


## Type of Numpy Array

---

- The array object in NumPy is called ndarray.
- We can create a NumPy ndarray object by using the array() function.

---


In [3]:
print(f"Type of Numpy array (ndarray): {type(arr)}")

Type of Numpy array (ndarray): <class 'numpy.ndarray'>


### To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [4]:
my_tuple = (1, 2, 3, 4)
tup_array = np.array(my_tuple)
print(f"Array created from Tuple: {tup_array}")

Array created from Tuple: [1 2 3 4]


In [5]:
my_list = [1, 2, 3, 4]
list_array = np.array(my_list)
print(f"Array created from List: {list_array}")

Array created from List: [1 2 3 4]


In [6]:
strr = "Hey there"
str_array = np.array(strr)
print(f"Array created from String: {str_array}")

Array created from String: Hey there


### String → 0-dimensional array because NumPy treats the entire string as a single scalar object, not individual characters. It doesn't split "Hey there" into ['H', 'e', 'y', ...].

- You can verify this:


In [7]:
string_array = np.array("Hey there")
print(f"Shape of the array: {string_array.shape}")  # ()  ← 0-d array, no dimensions
print(f"Number of dimensions: {string_array.ndim}")  # 0
print(
    f"Data Type of the array: {string_array.dtype}"
)  # <U9  (Unicode string of length 9)

Shape of the array: ()
Number of dimensions: 0
Data Type of the array: <U9


In [8]:
string_array_from_list = np.array(list("Hey there"))
print(f"Array (string_array_from_list): {string_array_from_list}")
print(f"Shape of the array: {string_array_from_list.shape}")
print(f"Number of dimensions: {string_array_from_list.ndim}")
print(f"Data Type of the array: {string_array_from_list.dtype}")

Array (string_array_from_list): ['H' 'e' 'y' ' ' 't' 'h' 'e' 'r' 'e']
Shape of the array: (9,)
Number of dimensions: 1
Data Type of the array: <U1


## Types of Arrays


#### 1. 0D Array: An array with exactly one single value


In [9]:
zero_d_array = np.array(42)
print(f"Array (zero_d_array): {zero_d_array}")
print(f"Shape of the array: {zero_d_array.shape}")
print(f"Dimensions of the array: {zero_d_array.ndim}")
print(f"Data Type of the array: {zero_d_array.dtype}")
print(f"Size(number of elements) of the array: {zero_d_array.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {zero_d_array.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {zero_d_array.nbytes}")

Array (zero_d_array): 42
Shape of the array: ()
Dimensions of the array: 0
Data Type of the array: int64
Size(number of elements) of the array: 1
Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: 8
Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: 8


#### 2. 1D Array (Vector): An array with exactly one single row


In [10]:
one_d_array = np.array([10, 20, 30, 40])
print(f"Array (one_d_array): {one_d_array}")
print(f"Shape of the array: {one_d_array.shape}")
print(f"Dimensions of the array: {one_d_array.ndim}")
print(f"Data Type of the array: {one_d_array.dtype}")
print(f"Size(number of elements) of the array: {one_d_array.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {one_d_array.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {one_d_array.nbytes}")

Array (one_d_array): [10 20 30 40]
Shape of the array: (4,)
Dimensions of the array: 1
Data Type of the array: int64
Size(number of elements) of the array: 4
Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: 8
Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: 32


#### 3. 2-D Arrays

---

- An array that has 1-D arrays as its elements is called a 2-D array.
- These are often used to represent matrix or 2nd order tensors.

---


In [11]:
two_d_array = np.array(
    [
        [10, 20, 30, 40],
        [100, 200, 300, 400],
        [1000, 2000, 3000, 4000],
        [10000, 20000, 30000, 40000],
        [100000, 200000, 300000, 400000],
    ]
)
print(f"Array (two_d_array): \n{two_d_array}")
print(f"Shape of the array: {two_d_array.shape}")
print(f"Dimensions of the array: {two_d_array.ndim}")
print(f"Data Type of the array: {two_d_array.dtype}")
print(f"Size(number of elements) of the array: {two_d_array.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {two_d_array.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {two_d_array.nbytes}")

Array (two_d_array): 
[[    10     20     30     40]
 [   100    200    300    400]
 [  1000   2000   3000   4000]
 [ 10000  20000  30000  40000]
 [100000 200000 300000 400000]]
Shape of the array: (5, 4)
Dimensions of the array: 2
Data Type of the array: int64
Size(number of elements) of the array: 20
Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: 8
Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: 160


#### 3. 3-D arrays

---

- An array that has 2-D arrays (matrices) as its elements is called 3-D array.
- These are often used to represent a 3rd order tensor.
- (Stack of matrices — like an RGB image (height, width, channels=3). Three axes.)

---


In [12]:
three_d_array = np.array(
    [
        [
            [10, 20, 30, 40],
            [100, 200, 300, 400],
            [1000, 2000, 3000, 4000],
            [10000, 20000, 30000, 40000],
            [100000, 200000, 300000, 400000],
        ],
        [
            [1.1, 2.1, 3.1, 4.1],
            [100.1, 200.1, 300.1, 400.1],
            [1000.1, 2000.1, 3000.1, 4000.1],
            [10000.1, 20000.1, 30000.1, 40000.1],
            [100000.1, 200000.1, 300000.1, 400000.1],
        ],
    ]
)
print(f"Array (three_d_array): \n{three_d_array}")
print(f"Shape of the array: {three_d_array.shape}")
print(f"Dimensions of the array: {three_d_array.ndim}")
print(f"Data Type of the array: {three_d_array.dtype}")
print(f"Size(number of elements) of the array: {three_d_array.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {three_d_array.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {three_d_array.nbytes}")

Array (three_d_array): 
[[[1.000000e+01 2.000000e+01 3.000000e+01 4.000000e+01]
  [1.000000e+02 2.000000e+02 3.000000e+02 4.000000e+02]
  [1.000000e+03 2.000000e+03 3.000000e+03 4.000000e+03]
  [1.000000e+04 2.000000e+04 3.000000e+04 4.000000e+04]
  [1.000000e+05 2.000000e+05 3.000000e+05 4.000000e+05]]

 [[1.100000e+00 2.100000e+00 3.100000e+00 4.100000e+00]
  [1.001000e+02 2.001000e+02 3.001000e+02 4.001000e+02]
  [1.000100e+03 2.000100e+03 3.000100e+03 4.000100e+03]
  [1.000010e+04 2.000010e+04 3.000010e+04 4.000010e+04]
  [1.000001e+05 2.000001e+05 3.000001e+05 4.000001e+05]]]
Shape of the array: (2, 5, 4)
Dimensions of the array: 3
Data Type of the array: float64
Size(number of elements) of the array: 40
Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: 8
Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: 320


#### 3. 4-D Array: Batch of 3D items. Used in ML — (batch_size, height, width, channels).


In [13]:
four_d_array = np.array(
    [
        [
            [
                [10, 20, 30, 40],
                [100, 200, 300, 400],
                [1000, 2000, 3000, 4000],
                [10000, 20000, 30000, 40000],
                [100000, 200000, 300000, 400000],
            ],
            [
                [1.1, 2.1, 3.1, 4.1],
                [100.1, 200.1, 300.1, 400.1],
                [1000.1, 2000.1, 3000.1, 4000.1],
                [10000.1, 20000.1, 30000.1, 40000.1],
                [100000.1, 200000.1, 300000.1, 400000.1],
            ],
        ],
        [
            [
                [10, 20, 30, 40],
                [100, 200, 300, 400],
                [1000, 2000, 3000, 4000],
                [10000, 20000, 30000, 40000],
                [100000, 200000, 300000, 400000],
            ],
            [
                [1.1, 2.1, 3.1, 4.1],
                [100.1, 200.1, 300.1, 400.1],
                [1000.1, 2000.1, 3000.1, 4000.1],
                [10000.1, 20000.1, 30000.1, 40000.1],
                [100000.1, 200000.1, 300000.1, 400000.1],
            ],
        ],
    ]
)
print(f"Array (four_d_array): \n{four_d_array}")
print(f"Shape of the array: {four_d_array.shape}")
print(f"Dimensions of the array: {four_d_array.ndim}")
print(f"Data Type of the array: {four_d_array.dtype}")
print(f"Size(number of elements) of the array: {four_d_array.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {four_d_array.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {four_d_array.nbytes}")

Array (four_d_array): 
[[[[1.000000e+01 2.000000e+01 3.000000e+01 4.000000e+01]
   [1.000000e+02 2.000000e+02 3.000000e+02 4.000000e+02]
   [1.000000e+03 2.000000e+03 3.000000e+03 4.000000e+03]
   [1.000000e+04 2.000000e+04 3.000000e+04 4.000000e+04]
   [1.000000e+05 2.000000e+05 3.000000e+05 4.000000e+05]]

  [[1.100000e+00 2.100000e+00 3.100000e+00 4.100000e+00]
   [1.001000e+02 2.001000e+02 3.001000e+02 4.001000e+02]
   [1.000100e+03 2.000100e+03 3.000100e+03 4.000100e+03]
   [1.000010e+04 2.000010e+04 3.000010e+04 4.000010e+04]
   [1.000001e+05 2.000001e+05 3.000001e+05 4.000001e+05]]]


 [[[1.000000e+01 2.000000e+01 3.000000e+01 4.000000e+01]
   [1.000000e+02 2.000000e+02 3.000000e+02 4.000000e+02]
   [1.000000e+03 2.000000e+03 3.000000e+03 4.000000e+03]
   [1.000000e+04 2.000000e+04 3.000000e+04 4.000000e+04]
   [1.000000e+05 2.000000e+05 3.000000e+05 4.000000e+05]]

  [[1.100000e+00 2.100000e+00 3.100000e+00 4.100000e+00]
   [1.001000e+02 2.001000e+02 3.001000e+02 4.001000e+02]


In [14]:
# e.g. 8 RGB images of 64×64 pixels
batch = np.zeros((8, 64, 64, 3)) # 8 rows, 64 columns, 
print(f"Array (four_d_array): \n{batch}")
print(f"Shape of the array: {batch.shape}")
print(f"Dimensions of the array: {batch.ndim}")
print(f"Data Type of the array: {batch.dtype}")
print(f"Size(number of elements) of the array: {batch.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {batch.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {batch.nbytes}")

Array (four_d_array): 
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]


 [[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  ...

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]
   ...
   [0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   

#### 4. 5-D Arrays: Used in video data, 3D scans, or deep architectures. Rare in everyday code.

In [15]:
# Video batch: (samples, frames, H, W, C)
vid_batch = np.zeros((4, 30, 224, 224, 3))
print(f"Array (four_d_array): \n{vid_batch}")
print(f"Shape of the array: {vid_batch.shape}") # (4, 30, 224, 224, 3)
# 4 videos, 30 frames each, 224×224 RGB
print(f"Dimensions of the array: {vid_batch.ndim}")  # 5
print(f"Data Type of the array: {vid_batch.dtype}")
print(f"Size(number of elements) of the array: {vid_batch.size}")
print(f"Memory in bytes used by one element. int32 = 4 bytes, float64 = 8 bytes, etc. for the array: {vid_batch.itemsize}")
print(f"Total memory = size x itemsize. Useful for checking how much RAM your array uses for the array: {vid_batch.nbytes}")

Array (four_d_array): 
[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   ...

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   ...

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]
    ...
    [0

#### 5. Higher Dimensional Arrays

In [16]:
higher = np.array([1, 2, 3, 4], ndmin=7)

print(higher)
print("Shape:", higher.shape)
print("Number of dimensions:", higher.ndim)

[[[[[[[1 2 3 4]]]]]]]
Shape: (1, 1, 1, 1, 1, 1, 4)
Number of dimensions: 7


In [17]:
my_list = [1, 2, 3, 4, 5]
my_np_array = np.array([1,2,3,4,5])
print(my_list*2)
print(my_np_array * 2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


In [18]:

# Use map to apply the lambda to every item
result = list(map(lambda i: i * 2, my_list))

print("Python list multiplication: ", result)

np_array = np.array([result])
print("Python array multiplication: ", list(map(lambda i: i*2, result)))

Python list multiplication:  [2, 4, 6, 8, 10]
Python array multiplication:  [4, 8, 12, 16, 20]


In [19]:
my_2d_np_array = np.array(
    [
        [1,2,3,4,5], 
        [10,20,30,40,50]
    ])
print(my_2d_np_array * 10000000000000)


[[ 10000000000000  20000000000000  30000000000000  40000000000000
   50000000000000]
 [100000000000000 200000000000000 300000000000000 400000000000000
  500000000000000]]


In [24]:
start_l = t.time()
py_list = [i*2 for i in range (100000)]
print("\n List operation time", t.time() - start_l)
00


 List operation time 0.015622377395629883


0

In [25]:
start_a = t.time()
np_arr = np.arange(100000) * 2  # pure NumPy, no Python loop
print("Numpy array operation time:", t.time() - start_a)


Numpy array operation time: 0.0013430118560791016


In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
existing = np.array([[1, 2, 3],
                     [4, 5, 6]])
np.ones_like(existing)  # → same shape (2,3), filled with 1s
# [[1, 1, 1],
#  [1, 1, 1]]

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.full((22,22), 7)

array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7,

In [56]:
random = np.random.random((2,3))
print("Random array: \n", random)

Random array: 
 [[0.53970867 0.71596433 0.24048336]
 [0.17681987 0.16052238 0.91274873]]


In [60]:
sequence = np.arange(0, 100, 2)
sequence

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Vector, Matrix, Tensor

## Vector — 1D Array
A single row of numbers.
```python
v = np.array([1, 2, 3])
# shape: (3,)
```

## Matrix — 2D Array
Rows and columns. Like a spreadsheet.
```python
m = np.array([[1, 2, 3],
              [4, 5, 6]])
# shape: (2, 3) → 2 rows, 3 columns
```

## Tensor — 3D Array
A stack of matrices. Like multiple spreadsheets layered on top of each other.
```python
t = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
# shape: (2, 2, 2) → 2 matrices, each 2×2
```

A real example you already know:
```python
img.shape  # (480, 640, 3) → this IS a tensor
#               │     │    └── 3 channels (BGR)
#               │     └─────── 640 columns
#               └───────────── 480 rows
```

---

| Name | Dims | Shape example | Real world |
|---|---|---|---|
| Vector | 1D | `(3,)` | A single pixel's BGR values |
| Matrix | 2D | `(480, 640)` | A grayscale image |
| Tensor | 3D | `(480, 640, 3)` | A color image |