# **NumPy Array Indexing**

______________________
- It means access Array Elements

- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
______________________

In [ ]:
import cv2
import numpy as np
# Load the image
img = cv2.imread("./images/japan_street.jpg") # this already creates a numpy array that we call imread function

# 'Crop' and show - remember: window name first, then the image
# cv2.imshow('Cropped Japan Street', img[0:100, 0:1000])

# print("Window opened. Press any key to close it.")
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.imshow('Cropped Japan Street', img[0:100, 0:1000])

In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[2] + arr[3]) 

7


## Access 2-D Arrays

In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2


## Access 3-D Arrays

Access the third element of the second array of the first array:

In [14]:
arr = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [7, 8, 9], 
            [10, 11, 12]
        ]
    ])
print(f"arr: \n{arr}")
print(arr[0, 1, 2]) 

arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Access the 1st element of the 2nd array of the 2nd array:

In [ ]:
print(f"arr: \n{arr}")
print(arr[1,1,0])

10


In [15]:
print(f"arr: \n{arr}")
print(arr[-1, -1, -1])

arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [26]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


In [17]:
print(img)

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [177 155 149]
  [190 168 162]
  [183 161 155]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [185 163 157]
  [179 157 151]
  [168 146 140]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [174 152 146]
  [167 145 139]
  [178 156 150]]

 ...

 [[ 32  33  29]
  [ 42  43  39]
  [ 38  39  35]
  ...
  [167 136 105]
  [179 149 120]
  [179 149 120]]

 [[ 38  39  35]
  [ 47  48  44]
  [ 35  36  32]
  ...
  [152 121  90]
  [137 107  78]
  [145 115  88]]

 [[ 40  41  37]
  [ 45  46  42]
  [ 24  25  21]
  ...
  [174 143 112]
  [188 158 131]
  [153 123  96]]]


In [18]:
print(img[-1,-1,-1]) # bottom-right pixel, Red channel value

96


In [19]:
print(img[0, 0, 0]) # top-left pixel, Blue channel value

24


In [25]:
print(img[0, 0, :] ) # top-left pixel, ALL 3 channel values → e.g. [24 30 29]

[24 30 29]
