# **NumPy Array Indexing**

______________________
- It means access Array Elements

- Array indexing is the same as accessing an array element.

- You can access an array element by referring to its index number.

- The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.
______________________

In [35]:
import cv2
import numpy as np
# Load the image
img = cv2.imread("./images/japan_street.jpg") # this already creates a numpy array that we call imread function

# 'Crop' and show - remember: window name first, then the image
# cv2.imshow('Japan Street', img)

# print("Window opened. Press any key to close it.")
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# cv2.imshow('Cropped Japan Street', img[0:100, 0:1000])

In [4]:
arr = np.array([1,2,3,4,5])
print(arr[2] + arr[3]) 

7


## Access 2-D Arrays

In [5]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  2


## Access 3-D Arrays

Access the third element of the second array of the first array:

In [6]:
arr = np.array(
    [
        [
            [1, 2, 3], 
            [4, 5, 6]
        ], 
        [
            [7, 8, 9], 
            [10, 11, 12]
        ]
    ])
print(f"arr: \n{arr}")
print(arr[0, 1, 2]) 

arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Access the 1st element of the 2nd array of the 2nd array:

In [7]:
print(f"arr: \n{arr}")
print(arr[1,1,0])

arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
10


In [8]:
print(f"arr: \n{arr}")
print(arr[-1, -1, -1])

arr: 
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [9]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


In [18]:
img.shape

(3264, 4928, 3)

In [19]:
img.ndim

3

In [10]:
print(img)

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [177 155 149]
  [190 168 162]
  [183 161 155]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [185 163 157]
  [179 157 151]
  [168 146 140]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [174 152 146]
  [167 145 139]
  [178 156 150]]

 ...

 [[ 32  33  29]
  [ 42  43  39]
  [ 38  39  35]
  ...
  [167 136 105]
  [179 149 120]
  [179 149 120]]

 [[ 38  39  35]
  [ 47  48  44]
  [ 35  36  32]
  ...
  [152 121  90]
  [137 107  78]
  [145 115  88]]

 [[ 40  41  37]
  [ 45  46  42]
  [ 24  25  21]
  ...
  [174 143 112]
  [188 158 131]
  [153 123  96]]]


In [11]:
print(img[-1,-1,-1]) # bottom-right pixel, Red channel value

96


In [12]:
print(img[0, 0, 0]) # top-left pixel, Blue channel value

24


In [13]:
print(img[0, 0, :] ) # top-left pixel, ALL 3 channel values → e.g. [24 30 29]

[24 30 29]


In [14]:
print(img[0:500, 0:1000])

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [149  63   0]
  [154  68   2]
  [152  66   0]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [152  66   0]
  [154  68   2]
  [151  65   0]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [152  66   0]
  [151  65   0]
  [148  62   0]]

 ...

 [[ 39  46  43]
  [ 30  37  34]
  [ 39  46  43]
  ...
  [ 17  22  25]
  [ 15  20  23]
  [ 14  19  22]]

 [[ 35  42  39]
  [ 32  39  36]
  [ 34  41  38]
  ...
  [ 15  20  23]
  [ 13  18  21]
  [ 12  17  20]]

 [[ 30  37  34]
  [ 32  39  36]
  [ 33  40  37]
  ...
  [ 14  19  22]
  [ 15  20  23]
  [ 15  20  23]]]


In [22]:
print(img[0:500])        # rows 0–499, ALL columns, ALL channels

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [177 155 149]
  [190 168 162]
  [183 161 155]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [185 163 157]
  [179 157 151]
  [168 146 140]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [174 152 146]
  [167 145 139]
  [178 156 150]]

 ...

 [[ 39  46  43]
  [ 30  37  34]
  [ 39  46  43]
  ...
  [178 160 153]
  [172 154 147]
  [177 159 152]]

 [[ 35  42  39]
  [ 32  39  36]
  [ 34  41  38]
  ...
  [188 170 163]
  [169 151 144]
  [174 156 149]]

 [[ 30  37  34]
  [ 32  39  36]
  [ 33  40  37]
  ...
  [189 171 164]
  [187 169 162]
  [179 161 154]]]


In [23]:
print(img[0:500, :])      # same thing, just explicit

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [177 155 149]
  [190 168 162]
  [183 161 155]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [185 163 157]
  [179 157 151]
  [168 146 140]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [174 152 146]
  [167 145 139]
  [178 156 150]]

 ...

 [[ 39  46  43]
  [ 30  37  34]
  [ 39  46  43]
  ...
  [178 160 153]
  [172 154 147]
  [177 159 152]]

 [[ 35  42  39]
  [ 32  39  36]
  [ 34  41  38]
  ...
  [188 170 163]
  [169 151 144]
  [174 156 149]]

 [[ 30  37  34]
  [ 32  39  36]
  [ 33  40  37]
  ...
  [189 171 164]
  [187 169 162]
  [179 161 154]]]


In [24]:
print(img[0:500, :, :]) # same thing, even more explicit

[[[ 24  30  29]
  [ 27  33  32]
  [ 31  37  36]
  ...
  [177 155 149]
  [190 168 162]
  [183 161 155]]

 [[ 21  27  26]
  [ 23  29  28]
  [ 27  33  32]
  ...
  [185 163 157]
  [179 157 151]
  [168 146 140]]

 [[ 31  37  36]
  [ 29  35  34]
  [ 29  35  34]
  ...
  [174 152 146]
  [167 145 139]
  [178 156 150]]

 ...

 [[ 39  46  43]
  [ 30  37  34]
  [ 39  46  43]
  ...
  [178 160 153]
  [172 154 147]
  [177 159 152]]

 [[ 35  42  39]
  [ 32  39  36]
  [ 34  41  38]
  ...
  [188 170 163]
  [169 151 144]
  [174 156 149]]

 [[ 30  37  34]
  [ 32  39  36]
  [ 33  40  37]
  ...
  [189 171 164]
  [187 169 162]
  [179 161 154]]]


In [16]:
print(img[1, 2, 0])  # row 1, col 2, Blue channel
print(img[1, 2, 1])  # row 1, col 2, Green channel
print(img[1, 2, 2])  # row 1, col 2, Red channel

27
33
32


In [17]:
# Or get all 3 channels of that pixel at once:
print(img[1, 2])     # row 1, col 2 → e.g. [255, 130, 80]  (B, G, R)
print(img[1, 2, :])  # same thing, just more explicit

[27 33 32]
[27 33 32]


In [27]:
print(img[0:500].shape) # we are only slicing rows (0 to 499) and columns and channels are untouched so we will get 500 rows, all the columns and all 3 channels

(500, 4928, 3)


In [28]:
print(img.shape)

(3264, 4928, 3)


In [29]:
print(img[:, 0:300].shape) # all 3264 rows, 300 columns and 3 channels

(3264, 300, 3)


In [30]:
print(img[100:200, 200:400].shape) # 100 rows (from 100-199) 200 columns (200-399) and 3 channels

(100, 200, 3)


In [32]:
print(img[:, :, 0].shape) # all rows, all columns 1 (1st) channel

(3264, 4928)


In [33]:
print(img[::2, ::2].shape) # Every second element from rows and every second element from columns and 3 channels

(1632, 2464, 3)


In [37]:
cv2.imread("./images/japan_street.jpg", 1)
cv2.imshow("CROPPED IMAGE", img[::2, ::2].shape)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [41]:
print(img[::-1].shape)  # step -1 → no skipping, going BACKWARD      → same shape

(3264, 4928, 3)


In [42]:
print(img[::-2].shape)  # step -2 → skip every other, going BACKWARD → smaller shape

(1632, 4928, 3)


In [48]:
print(img[1:5:2, 1:50:3, 0:2].shape)  # Rows 1&3, columns 1 to 49 every 3rd (1,4,7,...,49), Blue & Green channels only

(2, 17, 2)
