# Array Operations

In [1]:
import numpy as np

## Sort an Array 

In [2]:
unsorted_array = np.array([3,6,1,8,1,9])
np.sort(unsorted_array)

array([1, 1, 3, 6, 8, 9])

## Sorting a 2D Array

In [3]:
arr_2d_unsorted = np.array(
    [
        [3,1],
        [4,6],
        [0,10]
    ])

In [4]:
np.sort(arr_2d_unsorted, axis=0)

array([[ 0,  1],
       [ 3,  6],
       [ 4, 10]])

In [5]:
np.sort(arr_2d_unsorted, axis=1)

array([[ 1,  3],
       [ 4,  6],
       [ 0, 10]])

## Filtering Arrays

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Evens:", even_numbers)

Evens: [ 2  4  6  8 10]


## Filter with Mask

In [7]:
mask =  numbers > 5
print(mask)
print("Numbers > 10", numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers > 10 [ 6  7  8  9 10]


## Fancy Indexing VS np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [9]:
where_result = np.where(numbers > 5)
print(where_result)
print("np.where():", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
np.where(): [ 6  7  8  9 10]


In [10]:
condition_array = np.where(numbers > 5, numbers*4, numbers) # Any number that's greater than 5, multiply it by 4 ==> [ 1  2  3  4  5 24 28 32 36 40]
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Vectorized Operation

In [11]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

vectorized_op = arr1 + arr2
print(vectorized_op) #  Output = [7,  9, 11, 13, 15] Because NumPy adds element by element — index 0 with index 0, index 1 with index 1, and so on.

# arr1 = [1,  2,  3,  4,  5]
# arr2 = [6,  7,  8,  9, 10]
#         ↓   ↓   ↓   ↓   ↓
#      = [7,  9, 11, 13, 15]

# This is called vectorized operation — no loop needed, NumPy handles it internally in C, which is why it's fast.
# With a Python list, list1 + list2 would just concatenate them → [1,2,3,4,5,6,7,8,9,10]. NumPy's + actually does math.

[ 7  9 11 13 15]


## Combining two arrays

In [12]:
combined = np.concatenate([arr1, arr2])
combined

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Adding and Removing Data

In [15]:
arr = np.array([1, 2, 3])

new_arr = np.append(arr, 4)
new_arr   # [1 2 3 4]
np.append(arr, [4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [16]:
arr = np.array([1, 2, 3])

new_arr = np.insert(arr, 1, 99)
print(new_arr)   # [ 1 99  2  3]

[ 1 99  2  3]


In [17]:
arr = np.array([10, 20, 30, 40])

new_arr = np.delete(arr, 2)
print(new_arr)   # [10 20 40]

[10 20 40]


In [18]:
np.delete(arr, [0, 3])

array([20, 30])

In [19]:
arr = np.array([1, 2, 3, 3, 4])

new_arr = arr[arr != 3]
print(new_arr)   # [1 2 4]

[1 2 4]


## Array Compatibility

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9, 10])

print("Compatibility Shapes (a==b):", a.shape == b.shape)
print("Compatibility Shapes (a==c):", a.shape == c.shape)

Compatibility Shapes (a==b): True
Compatibility Shapes (a==c): False


In [28]:
original = np.array(
    [
        [1,2],
        [3,4],
    ])
new_row = np.array([[5,6]])
new_col = np.array([[7], [8]])
with_new_row = np.vstack((original, new_row))
print("with_new_row:\n",with_new_row)
with_new_col = np.hstack((original, new_col))
print("\nwith_new_col:\n",with_new_col)

with_new_row:
 [[1 2]
 [3 4]
 [5 6]]

with_new_col:
 [[1 2 7]
 [3 4 8]]
