# Array Operations

In [1]:
import numpy as np

## Sort an Array 

In [3]:
unsorted_array = np.array([3,6,1,8,1,9])
np.sort(unsorted_array)

array([1, 1, 3, 6, 8, 9])

## Sorting a 2D Array

In [4]:
arr_2d_unsorted = np.array(
    [
        [3,1],
        [4,6],
        [0,10]
    ])

In [7]:
np.sort(arr_2d_unsorted, axis=0)

array([[ 0,  1],
       [ 3,  6],
       [ 4, 10]])

In [8]:
np.sort(arr_2d_unsorted, axis=1)

array([[ 1,  3],
       [ 4,  6],
       [ 0, 10]])

## Filtering Arrays

In [10]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Evens:", even_numbers)

Evens: [ 2  4  6  8 10]


## Filter with Mask

In [17]:
mask =  numbers > 5
print(mask)
print("Numbers > 10", numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers > 10 [ 6  7  8  9 10]


## Fancy Indexing VS np.where()

In [13]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [16]:
where_result = np.where(numbers > 5)
print(where_result)
print("np.where():", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
np.where(): [ 6  7  8  9 10]


In [20]:
condition_array = np.where(numbers > 5, numbers*4, numbers) # Any number that's greater than 5, multiply it by 4 ==> [ 1  2  3  4  5 24 28 32 36 40]
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


## Vectorized Operation

In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

vectorized_op = arr1 + arr2
print(vectorized_op) #  Output = [7,  9, 11, 13, 15] Because NumPy adds element by element — index 0 with index 0, index 1 with index 1, and so on.

# arr1 = [1,  2,  3,  4,  5]
# arr2 = [6,  7,  8,  9, 10]
#         ↓   ↓   ↓   ↓   ↓
#      = [7,  9, 11, 13, 15]

# This is called vectorized operation — no loop needed, NumPy handles it internally in C, which is why it's fast.
# With a Python list, list1 + list2 would just concatenate them → [1,2,3,4,5,6,7,8,9,10]. NumPy's + actually does math.

[ 7  9 11 13 15]


## Adding and Removing Data

In [25]:
combined = np.concatenate([arr1, arr2])
combined

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])