# Image Data Analysis

In [ ]:
from pathlib import Path
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset_path = Path("./dataset/cats")
size = 64

X, y = [], []
classes = sorted([folder.name for folder in dataset_path.iterdir() if folder.is_dir()])

sizes = []

for label, d_class in enumerate(classes):
    directory = dataset_path / d_class

    for image in directory.iterdir():
        img = cv2.imread(str(image))

        if img is not None:
            h, w = img.shape[:2]
            sizes.append((w, h))

            img = cv2.resize(img, (size, size))
            X.append(img.flatten() / 255.0)
            y.append(label)

X = np.array(X)
y = np.array(y)

print("Classes:", classes)
print("Images:", len(X))
print("Features:", X.shape[1])
print("Example sizes:", sizes[:5])

Classes: ['bengal', 'domestic_shorthair', 'maine_coon', 'ragdoll', 'siamese']
Images: 420
Features: 12288
Example sizes: [(1250, 1390), (3024, 4032), (5184, 3456), (1200, 800), (1280, 853)]


## Analyze Brightness

In [6]:
brightness = img.mean()
print(int(brightness))

147


In [7]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
blur = cv2.Laplacian(gray, cv2.CV_64F).var()

print(gray)
print(blur)

[[ 50  55  57 ...  74  75  82]
 [ 51  54  60 ...  83  92  98]
 [ 58  54  58 ... 100 106 109]
 ...
 [ 95 103 115 ... 117 117 117]
 [ 89  99 108 ... 112 114 112]
 [ 83  95 105 ... 113 114 109]]
4302.035216331482
