# Array Operations

In [1]:
import numpy as np

## Sort an Array 

In [2]:
unsorted_array = np.array([3,6,1,8,1,9])
np.sort(unsorted_array)

array([1, 1, 3, 6, 8, 9])

## Sorting a 2D Array

In [3]:
arr_2d_unsorted = np.array(
    [
        [3,1],
        [4,6],
        [0,10]
    ])

In [4]:
np.sort(arr_2d_unsorted, axis=0)

array([[ 0,  1],
       [ 3,  6],
       [ 4, 10]])

In [5]:
np.sort(arr_2d_unsorted, axis=1)

array([[ 1,  3],
       [ 4,  6],
       [ 0, 10]])

In [6]:
np.sort(arr_2d_unsorted, axis=None)

array([ 0,  1,  3,  4,  6, 10])

## Sorting a 3D array

In [7]:
arr_3d_unsorted = np.array(
    [
        [
            [1,2,34,4],
            [11,32,344,48]
        ],
        [
            [141,23,134,40],
            [0,3,14,40]
        ]
    ]
)

In [8]:
arr_3d_unsorted.shape # (2, 2, 4):         axis 0   axis 1   axis 2
                               # shape →    2        2        4

# axis 0: 2 blocks
# axis 1: 2 Rows in each block
# axis 2: 4 Values (columns in each block)

(2, 2, 4)

In [9]:
np.sort(arr_3d_unsorted, axis=2)

array([[[  1,   2,   4,  34],
        [ 11,  32,  48, 344]],

       [[ 23,  40, 134, 141],
        [  0,   3,  14,  40]]])

In [10]:
np.sort(arr_3d_unsorted, axis=0)

array([[[  1,   2,  34,   4],
        [  0,   3,  14,  40]],

       [[141,  23, 134,  40],
        [ 11,  32, 344,  48]]])

In [11]:
np.sort(arr_3d_unsorted, axis=1)

array([[[  1,   2,  34,   4],
        [ 11,  32, 344,  48]],

       [[  0,   3,  14,  40],
        [141,  23, 134,  40]]])

## Sorting 4D Arrays

In [12]:
arr_4d_unsorted = np.array(

    [

        [

            [

                [42, 17, 91],
                [63, 28, 75],

            ],

            [

                [36, 84, 12],
                [57, 23, 68],

            ]

        ],

        [

            [

                [19, 73, 45],
                [82, 31, 64],

            ],

            [

                [27, 95, 53],
                [71, 14, 88],

            ]

        ]

    ]

)

print(arr_4d_unsorted.shape)

# Output: (2, 2, 2, 3)

print("""

Here Axis 0 is Batches | Outer Containers (2 Batches)

Here Axis 1 is Blocks | Depth (2 Block(s))

Here Axis 2 is Rows (2 Rows)

Here Axis 3 is Values | Columns (3 values in each row)

""")

(2, 2, 2, 3)


Here Axis 0 is Batches | Outer Containers (2 Batches)

Here Axis 1 is Blocks | Depth (2 Block(s))

Here Axis 2 is Rows (2 Rows)

Here Axis 3 is Values | Columns (3 values in each row)




In [13]:
np.sort(arr_4d_unsorted, axis=0)

array([[[[19, 17, 45],
         [63, 28, 64]],

        [[27, 84, 12],
         [57, 14, 68]]],


       [[[42, 73, 91],
         [82, 31, 75]],

        [[36, 95, 53],
         [71, 23, 88]]]])

In [14]:
np.sort(arr_4d_unsorted, axis=1)

array([[[[36, 17, 12],
         [57, 23, 68]],

        [[42, 84, 91],
         [63, 28, 75]]],


       [[[19, 73, 45],
         [71, 14, 64]],

        [[27, 95, 53],
         [82, 31, 88]]]])

In [15]:
np.sort(arr_4d_unsorted, axis=2)


array([[[[42, 17, 75],
         [63, 28, 91]],

        [[36, 23, 12],
         [57, 84, 68]]],


       [[[19, 31, 45],
         [82, 73, 64]],

        [[27, 14, 53],
         [71, 95, 88]]]])

In [16]:
np.sort(arr_4d_unsorted, axis=3)

array([[[[17, 42, 91],
         [28, 63, 75]],

        [[12, 36, 84],
         [23, 57, 68]]],


       [[[19, 45, 73],
         [31, 64, 82]],

        [[27, 53, 95],
         [14, 71, 88]]]])

## Sorting 5D Arrays

In [17]:
arr_5d_unsorted = np.array(

    [

        [

            [

                [
                    [42, 17, 91],
                    [63, 28, 75],
                ],

                [
                    [36, 84, 12],
                    [57, 23, 68],
                ]

            ],

            [

                [
                    [19, 73, 45],
                    [82, 31, 64],
                ],

                [
                    [27, 95, 53],
                    [71, 14, 88],
                ]

            ]

        ],

        [

            [

                [
                    [55, 26, 79],
                    [13, 68, 34],
                ],

                [
                    [91, 42, 17],
                    [36, 75, 23],
                ]

            ],

            [

                [
                    [64, 11, 83],
                    [29, 57, 46],
                ],

                [
                    [72, 38, 95],
                    [16, 84, 51],
                ]

            ]

        ]

    ]

)

print(arr_5d_unsorted.shape)

# Output: (2, 2, 2, 2, 3)

print("""

Here Axis 0 is Batches | Outer Containers (2 Batches)

Here Axis 1 is Blocks | Depth (2 Blocks)

Here Axis 2 is Groups | 2 Groups

Here Axis 3 is Rows (2 Rows)

Here Axis 4 is Values | Columns (3 values in each row)

""")

(2, 2, 2, 2, 3)


Here Axis 0 is Batches | Outer Containers (2 Batches)

Here Axis 1 is Blocks | Depth (2 Blocks)

Here Axis 2 is Groups | 2 Groups

Here Axis 3 is Rows (2 Rows)

Here Axis 4 is Values | Columns (3 values in each row)




## Filtering Arrays

In [18]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Evens:", even_numbers)

Evens: [ 2  4  6  8 10]


## Filter with Mask

In [19]:
mask =  numbers > 5
print(mask)
print("Numbers > 10", numbers[mask])

[False False False False False  True  True  True  True  True]
Numbers > 10 [ 6  7  8  9 10]


## Fancy Indexing VS np.where()

In [20]:
indices = [0,2,4]
print(numbers[indices])

[1 3 5]


In [21]:
where_result = np.where(numbers > 5)
print(where_result)
print("np.where():", numbers[where_result])

(array([5, 6, 7, 8, 9]),)
np.where(): [ 6  7  8  9 10]


In [22]:
condition_array = np.where(numbers > 5, numbers*4, numbers) # Any number that's greater than 5, multiply it by 4 ==> [ 1  2  3  4  5 24 28 32 36 40]
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [23]:
arr = np.array([-5, 3, -2, 8, 0, 12, -7, 4])

np.where(arr > 0)

(array([1, 3, 5, 7]),)

In [24]:
np.where(arr < 0, 0, arr) # (condition, value if true, value if false)

array([ 0,  3,  0,  8,  0, 12,  0,  4])

In [25]:
marks = np.array([45, 72, 33, 81, 59, 90, 27, 66])

np.where(marks >= 50, "Pass", "Fail")

array(['Fail', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Fail', 'Pass'],
      dtype='<U4')

In [26]:
arr = np.array([
    [12, 5, 23],
    [7, 31, 9],
    [18, 2, 40]
])

# Use np.where() to find the indexes
# of all values greater than 20.

np.where(arr > 20)

(array([0, 1, 2]), array([2, 1, 2]))

In [27]:
arr = np.array([
    [12, 5, 23],
    [7, 31, 9],
    [18, 2, 40]
])

# Use np.where() to replace values greater than 20 with 20.
# Keep all other values unchanged.
np.where(arr > 20, 20, arr)

array([[12,  5, 20],
       [ 7, 20,  9],
       [18,  2, 20]])

In [28]:
arr = np.array([
    [
        [5, 18, 3],
        [22, 7, 14]
    ],
    [
        [9, 31, 6],
        [12, 4, 27]
    ]
])

# Use np.where() to find the indexes
# of all values greater than 20.
np.where(arr > 20)

(array([0, 1, 1]), array([1, 0, 1]), array([0, 1, 2]))

In [29]:
arr = np.array([
    [
        [5, 18, 3],
        [22, 7, 14]
    ],
    [
        [9, 31, 6],
        [12, 4, 27]
    ]
])

# Use np.where() to:
# Replace values < 10 with 0
# Keep values >= 10 unchanged.
np.where(
    arr < 10,
    0,
    arr
)

array([[[ 0, 18,  0],
        [22,  0, 14]],

       [[ 0, 31,  0],
        [12,  0, 27]]])

In [30]:
arr = np.array([
    [
        [
            [12, 5, 28],
            [7, 31, 9]
        ],
        [
            [18, 2, 40],
            [15, 6, 11]
        ]
    ],
    [
        [
            [3, 25, 8],
            [42, 10, 17]
        ],
        [
            [21, 4, 33],
            [9, 14, 5]
        ]
    ]
])

# Use np.where() to find the indexes
# of all values greater than 30.
np.where(arr > 30)

(array([0, 0, 1, 1]),
 array([0, 1, 0, 1]),
 array([1, 0, 1, 0]),
 array([1, 2, 0, 2]))

In [31]:
arr = np.array([
    [
        [
            [
                [12, 5, 28],
                [7, 31, 9]
            ],
            [
                [18, 2, 40],
                [15, 6, 11]
            ]
        ]
    ],
    [
        [
            [
                [3, 25, 8],
                [42, 10, 17]
            ],
            [
                [21, 4, 33],
                [9, 14, 5]
            ]
        ]
    ]
])

# Use np.where() to:
# Replace values greater than 25 with 25
# Keep all other values unchanged.
np.where(arr > 25, 25, arr)

array([[[[[12,  5, 25],
          [ 7, 25,  9]],

         [[18,  2, 25],
          [15,  6, 11]]]],



       [[[[ 3, 25,  8],
          [25, 10, 17]],

         [[21,  4, 25],
          [ 9, 14,  5]]]]])

## Vectorized Operation

In [32]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

vectorized_op = arr1 + arr2
print(vectorized_op) #  Output = [7,  9, 11, 13, 15] Because NumPy adds element by element — index 0 with index 0, index 1 with index 1, and so on.

# arr1 = [1,  2,  3,  4,  5]
# arr2 = [6,  7,  8,  9, 10]
#         ↓   ↓   ↓   ↓   ↓
#      = [7,  9, 11, 13, 15]

# This is called vectorized operation — no loop needed, NumPy handles it internally in C, which is why it's fast.
# With a Python list, list1 + list2 would just concatenate them → [1,2,3,4,5,6,7,8,9,10]. NumPy's + actually does math.

[ 7  9 11 13 15]


In [33]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [34]:
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])

arr * 2

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]]])

In [35]:
arr = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ]
])

arr + 100

array([[[[101, 102],
         [103, 104]],

        [[105, 106],
         [107, 108]]]])

In [36]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr + np.array([10, 20, 30])

array([[11, 22, 33],
       [14, 25, 36]])

## Combining two arrays

In [37]:
combined = np.concatenate([arr1, arr2])
combined

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Adding and Removing Data

In [38]:
arr = np.array([1, 2, 3])

new_arr = np.append(arr, 4)
new_arr   # [1 2 3 4]
np.append(arr, [4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [39]:
arr = np.array([1, 2, 3])

new_arr = np.insert(arr, 1, 99)
print(new_arr)   # [ 1 99  2  3]

[ 1 99  2  3]


In [40]:
arr = np.array([10, 20, 30, 40])

new_arr = np.delete(arr, 2)
print(new_arr)   # [10 20 40]

[10 20 40]


In [41]:
np.delete(arr, [0, 3])

array([20, 30])

In [42]:
arr = np.array([1, 2, 3, 3, 4])

new_arr = arr[arr != 3]
print(new_arr)   # [1 2 4]

[1 2 4]


## Array Stacking
- `vstack()` and `hstack()`
- vstack → Vertical   → add Rows    ↓
- hstack → Horizontal → add Columns →

## Array compatibility
`Array compatibility:` The ability of two arrays to work together in a NumPy operation based on their shapes. For element-wise operations, shapes must match or satisfy NumPy's broadcasting rules. For stacking, the dimensions being joined must be compatible.

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9, 10])

print("Compatibility Shapes (a==b):", a.shape == b.shape)
print("Compatibility Shapes (a==c):", a.shape == c.shape)

Compatibility Shapes (a==b): True
Compatibility Shapes (a==c): False


In [44]:
original = np.array(
    [
        [1,2],
        [3,4],
    ])
new_row = np.array([[5,6]])
new_col = np.array([[7], [8]])
with_new_row = np.vstack((original, new_row))
print("with_new_row:\n",with_new_row)
with_new_col = np.hstack((original, new_col))
print("\nwith_new_col:\n",with_new_col)

with_new_row:
 [[1 2]
 [3 4]
 [5 6]]

with_new_col:
 [[1 2 7]
 [3 4 8]]


## Array Bradcasting
- Broadcasting is NumPy's ability to perform operations between arrays with different shapes by automatically expanding the smaller array when their shapes are compatible.


##### `1) Scalar broadcasting`

In [47]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

arr + 10

array([[11, 12, 13],
       [14, 15, 16]])

##### `2) 2D + 1D`

In [48]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

x = np.array([10, 20, 30])

arr + x

array([[11, 22, 33],
       [14, 25, 36]])

`3) Column broadcasting`

In [50]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

x = np.array([
    [10],
    [20]
])

arr + x

array([[11, 12, 13],
       [24, 25, 26]])

##### `When does broadcasting work?`

NumPy compares dimensions from the right side.

Two dimensions are compatible when:

- They are equal, OR
- One of them is 1.

For example:

    (2, 3) 
    (3,)

Think of (3,) as:

(1, 3)

Then:

(2, 3)

So broadcasting works.

But:

    (2, 3) \
    (2,)

does not work:

    (2, 3) \
    (1, 2)
-------
  

because 3 ≠ 2 and neither is 1.

## Array Aggregation
- Aggregation means combining multiple values into a single summary value.

In [51]:
arr = np.array([10, 20, 30, 40])
np.sum(arr)

np.int64(100)

#### `Common aggregation functions`

In [52]:
np.sum(arr)

np.int64(100)

In [53]:
np.mean(arr)

np.float64(25.0)

In [54]:
np.max(arr)

np.int64(40)

In [55]:
np.min(arr)

np.int64(10)

In [56]:
np.std(arr)

np.float64(11.180339887498949)

#### `Aggregation with 2D arrays`

In [57]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [58]:
np.sum(arr, axis=0)

array([5, 7, 9])

In [59]:
np.sum(arr, axis=1)

array([ 6, 15])