# *Random Numbers in NumPy*

In [37]:
import numpy as np
from numpy import random as rn

#### *`Generate Random Number`*
- NumPy offers the `random` module to work with random numbers.

In [38]:
x = rn.randint(100)
print(x) 

5


#### *`Generate Random Float`*

- The random module's `rand()` method returns a random float between 0 and 1.

In [39]:
x = rn.rand()

print(x)

0.10810135012059463


#### *`Generate Random Array`*

- In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

##### `Integers`

- The `randint()` method takes a size parameter where you can specify the shape of an array.
Example

- Generate a `1-D array` containing 5 random integers from 0 to 100:

In [40]:
arr = rn.randint(100, size=(5))
arr

array([55, 34, 12, 53, 97])

- Generate a `2-D array` with 3 rows, each row containing 5 random integers from 0 to 100:

In [41]:
arr_2d = rn.randint(100, size=(3, 5))
arr_2d

array([[68, 70, 43, 87, 13],
       [60, 11, 84, 74, 79],
       [45, 23, 87, 42, 27]])

#### *`Floats`*

- The `rand()` method also allows you to specify the shape of the array.
Example

- Generate a `1-D array` containing 5 random floats:

In [42]:
rn.rand(5)

array([0.40341657, 0.12131275, 0.79256584, 0.15744312, 0.89460975])

- Example

Generate a `2-D array` with 3 rows, each row containing 5 random numbers:

In [43]:
rn.rand(3, 5)

array([[0.67799404, 0.16479146, 0.9547688 , 0.81548657, 0.62732472],
       [0.32883951, 0.34097754, 0.92836573, 0.86565725, 0.18106908],
       [0.68550466, 0.51293085, 0.02472055, 0.86223407, 0.04396373]])

#### *`Generate Random Number From Array`*

- The `choice()` method allows you to generate a random value based on an array of values.

- The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [44]:
# Return one of the values in an array:
rn.choice([2,34,56,123,75,61,23,])

np.int64(2)

In [45]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
rn.choice([3, 5, 7], size=(3, 5))

array([[7, 3, 3, 3, 3],
       [3, 3, 3, 7, 3],
       [3, 3, 5, 3, 5]])