# *Random Numbers in NumPy*

In [3]:
import numpy as np
from numpy import random as rn

#### *`Generate Random Number`*
- NumPy offers the `random` module to work with random numbers.

In [10]:
x = rn.randint(100)
print(x) 

20


#### *`Generate Random Float`*

- The random module's `rand()` method returns a random float between 0 and 1.

In [11]:
x = rn.rand()

print(x)

0.29377397783768533


#### *`Generate Random Array`*

- In NumPy we work with arrays, and you can use the two methods from the above examples to make random arrays.

##### `Integers`

- The `randint()` method takes a size parameter where you can specify the shape of an array.
Example

- Generate a `1-D array` containing 5 random integers from 0 to 100:

In [13]:
arr = rn.randint(100, size=(5))
arr

array([63, 52,  7, 31, 40])

- Generate a `2-D array` with 3 rows, each row containing 5 random integers from 0 to 100:

In [15]:
arr_2d = rn.randint(100, size=(3, 5))
arr_2d

array([[57, 63, 63, 47, 17],
       [95, 85,  7, 20, 33],
       [27, 79,  5, 37, 58]])

#### *`Floats`*

- The `rand()` method also allows you to specify the shape of the array.
Example

- Generate a 1-D array containing 5 random floats:

In [16]:
rn.rand(5)

array([0.62443784, 0.71076374, 0.13478912, 0.77214111, 0.24315823])

- Example

Generate a `2-D array` with 3 rows, each row containing 5 random numbers:

In [17]:
rn.rand(3, 5)

array([[0.41986297, 0.45216597, 0.32424093, 0.91200482, 0.61906777],
       [0.60729451, 0.75853677, 0.85518024, 0.11683801, 0.96509751],
       [0.16006294, 0.78387265, 0.15127135, 0.49070468, 0.92854109]])

#### *`Generate Random Number From Array`*

- The `choice()` method allows you to generate a random value based on an array of values.

- The `choice()` method takes an array as a parameter and randomly returns one of the values.

In [37]:
# Return one of the values in an array:
rn.choice([2,34,56,123,75,61,23,])

np.int64(2)

In [47]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
rn.choice([3, 5, 7], size=(3, 5))

array([[7, 5, 3, 3, 5],
       [3, 5, 7, 5, 3],
       [7, 5, 7, 3, 5]])